/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGNTO = 5;
  /** RegularExpression Id. */
  int GOTO = 6;
  /** RegularExpression Id. */
  int MOVE = 7;
  /** RegularExpression Id. */
  int TURN = 8;
  /** RegularExpression Id. */
  int FACE = 9;
  /** RegularExpression Id. */
  int PUT = 10;
  /** RegularExpression Id. */
  int PICK = 11;
  /** RegularExpression Id. */
  int MOVETOTHE = 12;
  /** RegularExpression Id. */
  int MOVEINDIR = 13;
  /** RegularExpression Id. */
  int JUMPTOTHE = 14;
  /** RegularExpression Id. */
  int JUMPINDIR = 15;
  /** RegularExpression Id. */
  int NOP = 16;
  /** RegularExpression Id. */
  int ROBOTR = 17;
  /** RegularExpression Id. */
  int VARS = 18;
  /** RegularExpression Id. */
  int PROCS = 19;
  /** RegularExpression Id. */
  int BALLOONS = 20;
  /** RegularExpression Id. */
  int CHIPS = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int THEN = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int WHILE = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int REPEAT = 27;
  /** RegularExpression Id. */
  int FACING = 28;
  /** RegularExpression Id. */
  int CANPUT = 29;
  /** RegularExpression Id. */
  int CANPICK = 30;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 31;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 32;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 33;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int MAY = 37;
  /** RegularExpression Id. */
  int MIN = 38;
  /** RegularExpression Id. */
  int NOMB = 39;
  /** RegularExpression Id. */
  int NUM = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"assignTo\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"ROBOTR\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"repeat\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMoveInDir\"",
    "\"canJumpInDir\"",
    "\"canMoveToThe\"",
    "\"canJumpToThe\"",
    "\"not\"",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "<NOMB>",
    "<NUM>",
  };

}
